#!/bin/bash

dir=**/figure
rm $dir/ufigure.o
rm $dir/ufigure.ppu

dir=**/figure/**
rm $dir/add_i_down
rm $dir/add_i_down.o
rm $dir/add_i_left
rm $dir/add_i_left.o
rm $dir/add_i_right
rm $dir/add_i_right.o
rm $dir/add_i_top
rm $dir/add_i_top.o
rm $dir/add_j_down
rm $dir/add_j_down.o
rm $dir/add_j_left
rm $dir/add_j_left.o
rm $dir/add_j_right
rm $dir/add_j_right.o
rm $dir/add_j_top
rm $dir/add_j_top.o
rm $dir/add_l_down
rm $dir/add_l_down.o
rm $dir/add_l_left
rm $dir/add_l_left.o
rm $dir/add_l_right
rm $dir/add_l_right.o
rm $dir/add_l_top
rm $dir/add_l_top.o
rm $dir/add_o_down
rm $dir/add_o_down.o
rm $dir/add_o_left
rm $dir/add_o_left.o
rm $dir/add_o_right
rm $dir/add_o_right.o
rm $dir/add_o_top
rm $dir/add_o_top.o
rm $dir/add_s_down
rm $dir/add_s_down.o
rm $dir/add_s_left
rm $dir/add_s_left.o
rm $dir/add_s_right
rm $dir/add_s_right.o
rm $dir/add_s_top
rm $dir/add_s_top.o
rm $dir/add_t_down
rm $dir/add_t_down.o
rm $dir/add_t_left
rm $dir/add_t_left.o
rm $dir/add_t_right
rm $dir/add_t_right.o
rm $dir/add_t_top
rm $dir/add_t_top.o
rm $dir/add_z_down
rm $dir/add_z_down.o
rm $dir/add_z_left
rm $dir/add_z_left.o
rm $dir/add_z_right
rm $dir/add_z_right.o
rm $dir/add_z_top
rm $dir/add_z_top.o
rm $dir/add
rm $dir/add.o
rm $dir/deactivate
rm $dir/deactivate.o
rm $dir/delete
rm $dir/delete.o
rm $dir/is_on_the_bottom
rm $dir/is_on_the_bottom.o
rm $dir/move_down
rm $dir/move_down.o
rm $dir/move_left
rm $dir/move_left.o
rm $dir/move_right
rm $dir/move_right.o
rm $dir/next_orientation
rm $dir/next_orientation.o
rm $dir/read_form
rm $dir/read_form.o
rm $dir/read_orientation
rm $dir/read_orientation.o
rm $dir/read_position
rm $dir/read_position.o
rm $dir/rotate_right
rm $dir/rotate_right.o
rm $dir/write_form
rm $dir/write_form.o
rm $dir/write_orientation
rm $dir/write_orientation.o
rm $dir/write_position
rm $dir/write_position.o
